### ISSUE TITLE
Add option for the results to be sorted alphabetically

### ISSUE THREAD

**Issue by prajmus** [gaborbernat/pypi_changes#4]
It'd be nice if the output was sorted alphabetically. Sometimes you just want to check if package X is up to date. Its location will be indeterministic. If it was recently updated it'll be near top, but if it wasn't it's not easy to find.

**Describe the solution you'd like**
Add option to sort output alphabetically instead of by date.

**Comment by gaborbernat** [comment]
A PR in this direction would be welcomed  and accepted, thanks!
